[package]
name = "api42_rust_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15"
serde_json = "1.0.140"
reqwest = { version = "0.12.20", features = ["json", "rustls-tls"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3.31"